/**
 * 框圖以「頭像容器邊長」為 100%：`MASTER_AVATAR_FRAME_OVERLAY_PERCENT` **> 100** 時裝飾向外超出容器。
 * 圓形照片直徑 = `size * (MASTER_AVATAR_FRAME_OVERLAY_PERCENT / 100) * MASTER_AVATAR_HOLE_TO_FRAME_ASSET_RATIO`。
 */
export const MASTER_AVATAR_FRAME_OVERLAY_PERCENT = 160;

/** 素材「透明圓洞直徑／整張 PNG 邊長」（此圖透明洞約占整張 65%） */
export const MASTER_AVATAR_HOLE_TO_FRAME_ASSET_RATIO = 0.65;

/** 除錯用別名（等同框比例） */
export const FRAME_SIZE_PERCENT = MASTER_AVATAR_FRAME_OVERLAY_PERCENT;
